# Generated by Django 5.1.4 on 2025-06-14 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaluzNauki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва галузі науки')),
            ],
            options={
                'verbose_name': 'Галузь науки',
                'verbose_name_plural': 'Галузі науки',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science_field', models.CharField(blank=True, max_length=2550)),
                ('specialty', models.CharField(blank=True, max_length=2550)),
                ('title', models.CharField(max_length=1000)),
                ('link', models.URLField(blank=True, null=True)),
                ('issn', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_uk', models.CharField(max_length=255, unique=True)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Теми',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2500)),
                ('link', models.URLField(blank=True, default='Посилання відсутнє', max_length=2500, null=True)),
                ('doi', models.CharField(blank=True, max_length=2500, null=True)),
                ('author', models.CharField(blank=True, default='Автор відсутній', max_length=2500, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='knowledge.knowledgefield')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_uk', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='knowledge.subject')),
            ],
            options={
                'verbose_name': 'Підтема',
                'verbose_name_plural': 'Підтеми',
            },
        ),
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3000)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('article_link', models.URLField()),
                ('download_link', models.URLField(blank=True, null=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='knowledge.subtopic')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журнали',
            },
        ),
        migrations.CreateModel(
            name='Vidannya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('galuz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.galuznauki')),
            ],
            options={
                'verbose_name': 'Видання',
                'verbose_name_plural': 'Видання',
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journal_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.journalarticle')),
                ('vidannya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.vidannya')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'journal_article'), name='unique_favorite_journal'), models.UniqueConstraint(fields=('user', 'vidannya'), name='unique_favorite_vidannya')],
            },
        ),
    ]
