# Generated by Django 5.1.4 on 2024-12-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0011_alter_journalarticle_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science_field', models.CharField(blank=True, max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('issn', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
